/* This file is auto-generated by src/loader/scripts/meta_join.js */

/**
 * YUI 3 module metadata
 * @module loader
 * @submodule yui3
 */
YUI.Env[Y.version].modules = YUI.Env[Y.version].modules || {
    "arrow-wire": {
        "requires": [
            "wire-base"
        ]
    },
    "bezier-wire": {
        "requires": [
            "wire-base"
        ]
    },
    "bidirectional-arrow-wire": {
        "requires": [
            "wire-base"
        ]
    },
    "container": {
        "requires": [
            "container-base",
            "widget-icons"
        ],
        "skinnable": true
    },
    "container-base": {
        "requires": [
            "overlay",
            "widget-parent",
            "widget-child",
            "dd",
            "resize",
            "terminal-base",
            "wires-delegate"
        ]
    },
    "form-container": {
        "requires": [
            "container",
            "inputex-wirable-fields"
        ]
    },
    "image-container": {
        "requires": [
            "container-base"
        ]
    },
    "inout-container": {
        "requires": [
            "container"
        ]
    },
    "inputex-wirable": {
        "requires": [
            "terminal",
            "inputex-field"
        ]
    },
    "inputex-wirable-fields": {
        "use": [
            "inputex-wirable",
            "inputex-group",
            "inputex-string",
            "inputex-list"
        ]
    },
    "layer": {
        "requires": [
            "widget-parent",
            "container",
            "wires-delegate"
        ]
    },
    "silk-sprites": {
        "skinnable": true,
        "type": "css"
    },
    "straight-wire": {
        "requires": [
            "wire-base"
        ]
    },
    "terminal": {
        "requires": [
            "terminal-base",
            "terminal-dragedit",
            "terminal-scissors",
            "terminal-ddgroups"
        ]
    },
    "terminal-base": {
        "requires": [
            "widget",
            "widget-child",
            "widget-position",
            "widget-position-align",
            "wire-base",
            "wires-delegate"
        ]
    },
    "terminal-ddgroups": {
        "requires": [
            "terminal-dragedit"
        ]
    },
    "terminal-dragedit": {
        "use": [
            "bezier-wire",
            "dd-drop",
            "dd-drag",
            "dd-proxy"
        ]
    },
    "terminal-input": {
        "requires": [
            "terminal"
        ]
    },
    "terminal-output": {
        "requires": [
            "terminal"
        ]
    },
    "terminal-scissors": {
        "requires": [
            "overlay"
        ]
    },
    "textarea-container": {
        "requires": [
            "container"
        ]
    },
    "widget-icons": {
        "requires": [
            "silk-sprites"
        ]
    },
    "wire-base": {
        "requires": [
            "graphics"
        ],
        "skinnable": true
    },
    "wireit-app": {
        "requires": [
            "app",
            "handlebars",
            "model",
            "model-list",
            "json",
            "view",
            "layer",
            "bezier-wire",
            "anim"
        ]
    },
    "wires-delegate": {
        "requires": [
            "wire-base"
        ]
    }
};
YUI.Env[Y.version].md5 = 'f509e39dd648ecc79d0bd2c048fddbd3';
